import HarmonicAnalysisGeneralCompactGroupsCanonicalLaneLean.CompactGroupAdmissibleClass
import HarmonicAnalysisGeneralCompactGroupsCanonicalLaneLean.BridgeLemmas
import HarmonicAnalysisGeneralCompactGroupsCanonicalLaneLean.GateLemmas
import HarmonicAnalysisGeneralCompactGroupsCanonicalLaneLean.FinalTheorem
import HarmonicAnalysisGeneralCompactGroupsCanonicalLaneLean.FourierAnalysisPackage
import HarmonicAnalysisGeneralCompactGroupsCanonicalLaneLean.PeterWeylTheoremPackage
import HarmonicAnalysisGeneralCompactGroupsCanonicalLaneLean.AbstractHarmonicAnalysisFoundation

namespace HautevilleHouse
namespace HarmonicAnalysisGeneralCompactGroupsCanonicalLaneLean

-- This module is the root of the HarmonicAnalysisGeneralCompactGroupsCanonicalLaneLean Lean proof package.

end HarmonicAnalysisGeneralCompactGroupsCanonicalLaneLean
end HautevilleHouse
